version: '3'
services:
  nginx:
    image: really/nginx-certbot
    volumes:
      - ./nginx/nginx:/etc/nginx/conf.d:rw
      - ./nginx/letsencrypt:/etc/letencrypt:rw
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - th
    links:
      - th
    restart: unless-stopped
  th:
    image: frbsc/tilehut:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./tiles:/tilehut/data:rw
    ports:
      - 8000:8000
    restart: unless-stopped
  