version: '3'
services:
  nginx:
    image: really/nginx-certbot
    volumes:
      - ./nginx/nginx:/etc/nginx/conf.d:rw
      - ./nginx/letsencrypt:/etc/letsencrypt:rw
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - th
    links:
      - th
    restart: unless-stopped
  th:
    image: frbsc/tilehut:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./tiles:/tilehut/data:ro
    ports:
      - 8000:8000
    restart: unless-stopped
  ftp:
    image: atmoz/sftp
    volumes:
      - ./tiles:/home/gis/tiles:rw
      - ./pub_keys:/home/gis/.ssh/keys:ro
      - ./hos_keys:/etc/ssh:rw
    ports:
      - "2222:22"
    command: gis::::tiles
    depends_on: th
    restart: unless-stopped